// infos.go
package mypriorityoptimizer

var (
	InfoPluginReady                         = "plugin ready"
	InfoWaitingForInformers                 = "waiting for informers to sync"
	InfoInformersSynced                     = "informers synced"
	InfoUsableNodeFound                     = "usable node found"
	InfoCacheWarmedUp                       = "cache warmed up"
	InfoGetNodesFailed                      = "getNodes failed"
	InfoNoop                                = "no operation"
	InfoNoActivePlan                        = "no active plan"
	InfoNoPlanProvided                      = "no plan provided"
	InfoActivePlanInProgress                = "active plan is in progress"
	InfoNoStrategyEnabled                   = "no strategy enabled"
	InfoBlockPod                            = "blocking pod"
	InfoPendingPod                          = "pending pod"
	InfoNoBlockedPods                       = "no blocked pods"
	InfoPinPod                              = "pin pod"
	InfoAllowPod                            = "allow pod"
	InfoPlanCompleted                       = "plan completed"
	InfoSolverFailed                        = "solver failed"
	InfoNoSolverEnabled                     = "no solver enabled"
	InfoPlanCompletionFailed                = "plan completion check failed"
	InfoPlanRegistrationFailed              = "register plan failed"
	InfoPlanActivationFailed                = "plan activation failed"
	InfoNominatedAfterPlan                  = "nominated after plan execution"
	InfoPlanPreparationFailed               = "plan preparation failed"
	InfoNoPendingPods                       = "no pending pods"
	InfoNoPendingPodsToSchedule             = "no pending pods to schedule"
	InfoNoFeasibleOrOptimalSolution         = "no feasible or optimal solution"
	InfoNoImprovingSolutionFromAnySolver    = "no improving solution from any solver"
	InfoNoImprovement                       = "no improvement"
	InfoCachesNotWarmedUp                   = "caches not warmed up yet"
	InfoInformersCanceledOrTimedOut         = "informers sync canceled or timed out"
	InfoWaitForUsableNodeCanceledOrTimedOut = "wait for usable node canceled or timed out"
	InfoPlanExecutionFinished               = "plan execution finished; waiting for settlement"
	InfoCycleStarted                        = "cycle started"
	InfoCycleStartedFirstRun                = "started; first run scheduled"
	InfoCycleNextRun                        = "next run"
	InfoPodPlacedByName                     = "pod placed by name"
	InfoPlanNotApplicable                   = "plan not applicable"
	InfoDeactivatingActivePlan              = "deactivating active plan"
	InfoActivatingPlannedPendingPods        = "activating planned pending pods"
	InfoNoUsableNodes                       = "no usable nodes available"
)
