apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: redis1
spec:
  selector:
    matchLabels:
      app: redis1
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis1
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis1
spec:
  type: NodePort
  selector:
    app: redis1
  ports:
    - protocol: TCP
      port: 6379
