#!/usr/bin/env bash
set -euo pipefail

# ------------------ Detect target user/home --------------------
pick_target_user() {
  if [ "$(id -u)" -eq 0 ]; then
    if [ -n "${SUDO_USER:-}" ] && [ "${SUDO_USER}" != "root" ]; then
      echo "${SUDO_USER}"; return
    fi
    getent passwd | awk -F: '$3>=1000 && $1!="nobody"{print $1; exit}'
  else
    id -un
  fi
}
TARGET_USER="${TARGET_USER:-$(pick_target_user)}"
TARGET_HOME="$(eval echo "~${TARGET_USER}")"

# ------------------ Repo paths ------------------
REPO_URL="${REPO_URL:-https://github.com/henrikdchristensen/scheduler-plugins}"
REPO_BRANCH="${REPO_BRANCH:-henrikdc-cross-preemp}"
REPO_DIR="${REPO_DIR:-${TARGET_HOME}/scheduler-plugins}"
BOOTSTRAP_DIR="${BOOTSTRAP_DIR:-${REPO_DIR}/bootstrap}"

# ------------------ One-level names ------------------
KWOK_CLUSTER="${KWOK_CLUSTER:-kwok1}"
KWOK_CONFIGS="${KWOK_CONFIGS:-baseline}"
KWOK_SEEDS="${KWOK_SEEDS:-seeds001.txt}"

# ------------------ Helpers ------------------
run_root() { [ "$(id -u)" -eq 0 ] && bash -lc "$*" || sudo bash -lc "$*"; }
run_as_target() {
  if [ "$(id -un)" = "${TARGET_USER}" ]; then bash -lc "$*"; else sudo -iu "${TARGET_USER}" bash -lc "$*"; fi
}

# ------------------ Minimal prereqs (git only) ------------------
echo "[init] installing base packages (git, ca-certificates)"
run_root "export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends git ca-certificates"

# ------------------ Clone/update repo ------------------
if [ ! -d "${REPO_DIR}/.git" ]; then
  echo "[init] cloning ${REPO_URL} (branch=${REPO_BRANCH}) into ${REPO_DIR}"
  run_as_target "git clone --branch '${REPO_BRANCH}' --single-branch '${REPO_URL}' '${REPO_DIR}'"
else
  echo "[init] repo exists; updating branch=${REPO_BRANCH}"
  run_as_target "git -C '${REPO_DIR}' fetch --all --prune &&
                 git -C '${REPO_DIR}' checkout '${REPO_BRANCH}' &&
                 git -C '${REPO_DIR}' pull --ff-only"
fi
run_root "chown -R '${TARGET_USER}:${TARGET_USER}' '${REPO_DIR}'"

# ------------------ Persist names ------------------
KWOKRC="${REPO_DIR}/.kwokrc"
cat > "${KWOKRC}" <<EOF
# Autogenerated by bootstrap/00_init.sh
export KWOK_CLUSTER=${KWOK_CLUSTER}
export KWOK_CONFIGS=${KWOK_CONFIGS}
export KWOK_SEEDS=${KWOK_SEEDS}
EOF
run_root "chown '${TARGET_USER}:${TARGET_USER}' '${KWOKRC}'"
echo "[init] wrote ${KWOKRC}: cluster=${KWOK_CLUSTER} configs=${KWOK_CONFIGS} seeds=${KWOK_SEEDS}"

# ------------------ Normalize + exec bits ------------------
for f in "${BOOTSTRAP_DIR}/01_system_setup.sh" "${BOOTSTRAP_DIR}/02_build_test.sh"; do
  [ -f "$f" ] || continue
  sed -i '1s/^\xEF\xBB\xBF//' "$f" || true
  sed -i 's/\r$//' "$f" || true
  run_root "chmod +x '$f'"
done

# ------------------ System setup (root) ------------------
echo "[init] 01_system_setup.sh (Docker, buildx, kubectl, kwokctl, minimal Python)"
run_root "/usr/bin/env bash '${BOOTSTRAP_DIR}/01_system_setup.sh'"

# Ensure target user is in docker group
if command -v docker >/dev/null 2>&1 && ! id -nG "${TARGET_USER}" | tr ' ' '\n' | grep -qx docker; then
  echo "[init] adding ${TARGET_USER} to docker group"
  run_root "usermod -aG docker '${TARGET_USER}'"
fi

# ------------------ Build + tests (user) ------------------
echo "[init] 02_build_test.sh (runs as ${TARGET_USER})"
run_as_target "/usr/bin/env bash '${BOOTSTRAP_DIR}/02_build_test.sh'"

echo "[done] Initialization completed. Repo: ${REPO_DIR}"
