#!/usr/bin/env bash
set -euo pipefail

# ------------------ Detect target user/home --------------------
pick_target_user() {
  if [ "$(id -u)" -eq 0 ]; then
    if [ -n "${SUDO_USER:-}" ] && [ "${SUDO_USER}" != "root" ]; then
      echo "${SUDO_USER}"; return
    fi
    getent passwd | awk -F: '$3>=1000 && $1!="nobody"{print $1; exit}'
  else
    id -un
  fi
}
TARGET_USER="${TARGET_USER:-$(pick_target_user)}"
TARGET_HOME="$(eval echo "~${TARGET_USER}")"

# ------------------ Repo paths ------------------
REPO_URL="${REPO_URL:-https://github.com/henrikdchristensen/scheduler-plugins}"
REPO_BRANCH="${REPO_BRANCH:-henrikdc-cross-preemp}"
REPO_DIR="${REPO_DIR:-${TARGET_HOME}/scheduler-plugins}"
BOOTSTRAP_DIR="${BOOTSTRAP_DIR:-${REPO_DIR}/bootstrap}"   # this file's directory in repo

# ------------------ One-level "names" set here ------------------
# You can override these in Vagrantfile via env:
#   KWOK_CLUSTER=kwok2  KWOK_CONFIGS=baseline  KWOK_SEEDS=seeds001.txt
KWOK_CLUSTER="${KWOK_CLUSTER:-kwok1}"          # just a name, not a path
KWOK_CONFIGS="${KWOK_CONFIGS:-baseline}"       # subdir under scripts/kwok/configs/
KWOK_SEEDS="${KWOK_SEEDS:-seeds001.txt}"       # file under scripts/kwok/seeds/

# ------------------ Helpers ------------------
run_root() {
  if [ "$(id -u)" -eq 0 ]; then bash -lc "$*"; else sudo bash -lc "$*"; fi
}
run_as_target() {
  if [ "$(id -un)" = "${TARGET_USER}" ]; then
    bash -lc "$*"
  else
    sudo -iu "${TARGET_USER}" bash -lc "$*"
  fi
}

# Normalize shell scripts once (strip BOM + CRLF) and make them exec
normalize_bootstrap() {
  for f in "${BOOTSTRAP_DIR}/00_init.sh" \
           "${BOOTSTRAP_DIR}/01_system_setup.sh" \
           "${BOOTSTRAP_DIR}/02_build_test.sh"; do
    [ -f "$f" ] || continue
    # strip UTF-8 BOM if present (first line only)
    sed -i '1s/^\xEF\xBB\xBF//' "$f" || true
    # strip CR from CRLF
    sed -i 's/\r$//' "$f" || true
    chmod +x "$f" || true
  done
}
normalize_bootstrap


# ------------------ Minimal OS prereqs ------------------
echo "[init] installing base packages (git, curl, ca-certificates, python3, venv, pip, jq)…"
run_root "export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y git curl ca-certificates python3 python3-venv python3-pip jq"

# ------------------ Clone/update repo (owned by TARGET_USER) ----
if [ ! -d "${REPO_DIR}/.git" ]; then
  echo "[init] cloning ${REPO_URL} (branch=${REPO_BRANCH}) into ${REPO_DIR}"
  run_as_target "git clone --branch '${REPO_BRANCH}' --single-branch '${REPO_URL}' '${REPO_DIR}'"
else
  echo "[init] repo exists; updating branch=${REPO_BRANCH}"
  run_as_target "git -C '${REPO_DIR}' fetch --all --prune &&
                 git -C '${REPO_DIR}' checkout '${REPO_BRANCH}' &&
                 git -C '${REPO_DIR}' pull --ff-only"
fi
run_root "chown -R '${TARGET_USER}:${TARGET_USER}' '${REPO_DIR}'"

# ------------------ Persist the names in REPO/.kwokrc -----------
KWOKRC="${REPO_DIR}/.kwokrc"
cat > "${KWOKRC}" <<EOF
# Autogenerated by bootstrap/00_init.sh
export KWOK_CLUSTER=${KWOK_CLUSTER}
export KWOK_CONFIGS=${KWOK_CONFIGS}
export KWOK_SEEDS=${KWOK_SEEDS}
EOF
run_root "chown '${TARGET_USER}:${TARGET_USER}' '${KWOKRC}'"
echo "[init] wrote ${KWOKRC}: cluster=${KWOK_CLUSTER} configs=${KWOK_CONFIGS} seeds=${KWOK_SEEDS}"

# ------------------ Make bootstrap scripts executable -----------
run_root "chmod +x '${BOOTSTRAP_DIR}'/01_system_setup.sh '${BOOTSTRAP_DIR}'/02_build_test.sh"

# ------------------ System-level setup (Docker, Go, kubectl, kwokctl)
echo "[init] 01_system_setup.sh (Docker, Go, kubectl, kwokctl)"
run_root "/usr/bin/env bash '${BOOTSTRAP_DIR}/01_system_setup.sh'"

# ------------------ Add TARGET_USER to docker group -------------
if command -v docker >/dev/null 2>&1; then
  if ! id -nG "${TARGET_USER}" | tr ' ' '\n' | grep -qx docker; then
    echo "[init] adding ${TARGET_USER} to docker group"
    run_root "usermod -aG docker '${TARGET_USER}'"
  fi
else
  echo "[warn] docker not found after 01_system_setup.sh"
fi

# ------------------ User-level build + tests --------------------
echo "[init] 02_build_test.sh (runs as ${TARGET_USER})"
run_as_target "/usr/bin/env bash '${BOOTSTRAP_DIR}/02_build_test.sh'"

echo "[done] Initialization completed. Repo: ${REPO_DIR}"
