# bootstrap/00_init.sh
#!/usr/bin/env bash
set -euo pipefail
trap 'echo "[error] init failed at line $LINENO"; exit 1' ERR

########################## HELPER FUNCTIONS ##########################
######################################################################

# Determine the target user to run as non-root (first user with UID >= 1000)
# and to run as root (e.g. via sudo), use SUDO_USER.
pick_target_user() {
  if [ "$(id -u)" -eq 0 ]; then
    if [ -n "${SUDO_USER:-}" ] && [ "${SUDO_USER}" != "root" ]; then
      echo "${SUDO_USER}"; return
    fi
    getent passwd | awk -F: '$3>=1000 && $1!="nobody"{print $1; exit}'
  else
    id -un
  fi
}
run_root() {
  [ "$(id -u)" -eq 0 ] && bash -lc "$*" || sudo bash -lc "$*";
}
run_as_target() {
  if [ "$(id -un)" = "${TARGET_USER}" ]; then
    bash -lc "$*";
  else
    sudo -iu "${TARGET_USER}" bash -lc "$*";
  fi;
}

# Start time measurement
echo "[init] starting init script: $(date +%Y%m%d_%H%M%S)"

TARGET_USER="${TARGET_USER:-$(pick_target_user)}"
TARGET_HOME="$(eval echo "~${TARGET_USER}")" # home directory of the target user

REPO_NAME="scheduler-plugins"
GITHUB_URL="https://github.com/henrikdchristensen"
REPO_BRANCH="henrikdc-cross-preemp"
REPO_URL="${GITHUB_URL}/${REPO_NAME}"

REPO_DIR="${TARGET_HOME}/${REPO_NAME}"
BOOTSTRAP_DIR="${REPO_DIR}/bootstrap"

############# MAIN CONFIGURATION VARIABLES ####################
###############################################################
KWOK_CLUSTER="${KWOK_CLUSTER:-kwok1}"
KWOK_CONFIGS="${KWOK_CONFIGS:-baseline}"
KWOK_SEEDS="${KWOK_SEEDS:-seeds001.txt}"
KWOK_RUNTIME="${KWOK_RUNTIME:-binary}"   # binary | docker

echo "[init] cluster=${KWOK_CLUSTER} configs=${KWOK_CONFIGS} seeds=${KWOK_SEEDS} runtime=${KWOK_RUNTIME}"

# Fail fast
if [ -z "${TARGET_USER:-}" ] || [ -z "${TARGET_HOME:-}" ]; then
  echo "[error] could not resolve TARGET_USER/TARGET_HOME"; exit 1
fi
if ! command -v sudo >/dev/null 2>&1 && [ "$(id -u)" -ne 0 ]; then
  echo "[error] sudo not available and not running as root"; exit 1
fi
if [ "${KWOK_RUNTIME}" != "binary" ] && [ "${KWOK_RUNTIME}" != "docker" ]; then
  echo "[error] KWOK_RUNTIME must be 'binary' or 'docker' (got: ${KWOK_RUNTIME})"; exit 1
fi

echo "[init] installing base packages (git, ca-certificates, curl, make)"
# Use DEBIAN_FRONTEND=noninteractive to avoid any interactive prompts
run_root "export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends git ca-certificates curl make"
echo "[ok] base packages installed"

echo "[init] cloning ${REPO_URL} (branch=${REPO_BRANCH}) into ${REPO_DIR}"
# Use --single-branch to avoid cloning all branches
run_as_target "git clone --branch '${REPO_BRANCH}' --single-branch '${REPO_URL}' '${REPO_DIR}'"
run_root "chown -R '${TARGET_USER}:${TARGET_USER}' '${REPO_DIR}'"
echo "[ok] cloned ${REPO_URL} into ${REPO_DIR}"

# Write env vars to .kwokrc for reuse or reference
# Write them to repo directory
echo "[init] writing configuration to ${REPO_DIR}/.kwokrc"
KWOKRC="${REPO_DIR}/.kwokrc"
cat > "${KWOKRC}" <<EOF
# Generated by 00_init.sh
export KWOK_CLUSTER=${KWOK_CLUSTER}
export KWOK_CONFIGS=${KWOK_CONFIGS}
export KWOK_SEEDS=${KWOK_SEEDS}
export KWOK_RUNTIME=${KWOK_RUNTIME}
EOF
run_root "chown '${TARGET_USER}:${TARGET_USER}' '${KWOKRC}'"
echo "[init] wrote ${KWOKRC}: cluster=${KWOK_CLUSTER} configs=${KWOK_CONFIGS} seeds=${KWOK_SEEDS} runtime=${KWOK_RUNTIME}"

# Ensure scripts are Unix format and executable
# Mainly for Windows users who may have cloned with CRLF line endings
echo "[init] ensuring scripts are Unix format and executable"
for f in "${BOOTSTRAP_DIR}/01_system_setup.sh" "${BOOTSTRAP_DIR}/02_build_test.sh"; do
  [ -f "$f" ] || continue
  sed -i '1s/^\xEF\xBB\xBF//' "$f" || true
  sed -i 's/\r$//' "$f" || true
  run_root "chmod +x '$f'"
done
echo "[ok] scripts are Unix format and executable"

# Run the setup scripts as root
echo "[init] 01_system_setup.sh (install kubectl, kwokctl+kwok, Python; Docker if runtime=docker)"
run_root "/usr/bin/env bash '${BOOTSTRAP_DIR}/01_system_setup.sh'"
echo "[ok] system setup done with runtime=${KWOK_RUNTIME} $(date +%Y%m%d_%H%M%S)"

# Ensure TARGET_USER is in docker group if docker installed
# Ensure TARGET_USER is in docker group if docker runtime selected
if [ "${KWOK_RUNTIME}" = "docker" ]; then
  if ! command -v docker >/dev/null 2>&1; then
    echo "[error] docker runtime selected but docker is not installed"; exit 1
  fi
  if ! id -nG "${TARGET_USER}" | tr ' ' '\n' | grep -qx docker; then
    echo "[init] adding ${TARGET_USER} to docker group"
    run_root "usermod -aG docker '${TARGET_USER}'"
  fi
fi

# Run the build/test scripts as TARGET_USER
echo "[init] 02_build_test.sh (runs as ${TARGET_USER})"
run_as_target "/usr/bin/env bash '${BOOTSTRAP_DIR}/02_build_test.sh'"
echo "[ok] build/test done $(date +%Y%m%d_%H%M%S)"

# Done
echo "[done] Initialization completed"
