# bootstrap/bootstrap.sh
#!/usr/bin/env bash
set -euo pipefail

# ---------------------------- CONFIG DEFAULTS -------------------------------
REPO_OWNER="${REPO_OWNER:-henrikdchristensen}"
REPO_NAME="${REPO_NAME:-scheduler-plugins}"
REPO_BRANCH="${REPO_BRANCH:-henrikdc-cross-preemp}"
REPO_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}"

KWOK_CLUSTER="${KWOK_CLUSTER:-kwok1}"
KWOK_CONFIGS="${KWOK_CONFIGS:-baseline}"
KWOK_SEEDS="${KWOK_SEEDS:-seeds001.txt}"
KWOK_RUNTIME="${KWOK_RUNTIME:-binary}"  # binary | docker

KUBECTL_VERSION="${KUBECTL_VERSION:-v1.32.7}"
KWOK_VERSION="${KWOK_VERSION:-v0.7.0}"
GO_VERSION="${GO_VERSION:-1.24.3}"
GO_ARCH="${GO_ARCH:-amd64}"

# Docker image tag used for docker runtime builds
SCHED_IMAGE_TAG="${SCHED_IMAGE_TAG:-localhost:5000/scheduler-plugins/kube-scheduler:dev}"

# ------------------------------ HELPERS -------------------------------------
log() { printf '[%s] %s\n' "$1" "$2"; }
die() { log "error" "$1"; exit 1; }

pick_target_user() {
  if [ "$(id -u)" -eq 0 ]; then
    if [ -n "${SUDO_USER:-}" ] && [ "${SUDO_USER}" != "root" ]; then
      echo "${SUDO_USER}"; return
    fi
    getent passwd | awk -F: '$3>=1000 && $1!="nobody"{print $1; exit}'
  else
    id -un
  fi
}

run_root() {
  if [ "$(id -u)" -eq 0 ]; then bash -lc "$*"; else sudo bash -lc "$*"; fi
}

run_as() {
  local user="$1"; shift
  if [ "$(id -un)" = "${user}" ]; then
    bash -lc "$*"
  else
    sudo -iu "${user}" bash -lc "$*"
  fi
}

# ------------------------------ PATHS ---------------------------------------
TARGET_USER="${TARGET_USER:-$(pick_target_user)}"
[ -n "${TARGET_USER}" ] || die "could not resolve target user"
TARGET_HOME="$(eval echo "~${TARGET_USER}")"
REPO_DIR="${REPO_DIR:-${TARGET_HOME}/${REPO_NAME}}"
BOOT_DIR="${BOOT_DIR:-${REPO_DIR}/bootstrap}"
KWOKRC="${REPO_DIR}/.kwokrc"

# --------------------------- WRITE/READ .kwokrc -----------------------------
write_kwokrc() {
  log init "writing ${KWOKRC}"
  cat > "${KWOKRC}" <<EOF
# Generated by bootstrap.sh
export KWOK_CLUSTER=${KWOK_CLUSTER}
export KWOK_CONFIGS=${KWOK_CONFIGS}
export KWOK_SEEDS=${KWOK_SEEDS}
export KWOK_RUNTIME=${KWOK_RUNTIME}
export SCHED_IMAGE_TAG=${SCHED_IMAGE_TAG}
EOF
  run_root "chown '${TARGET_USER}:${TARGET_USER}' '${KWOKRC}'"
}

# shellcheck disable=SC1090
read_kwokrc() {
  [ -f "${KWOKRC}" ] || die "missing ${KWOKRC} (run 'setup' first)"
  # shellcheck disable=SC1091
  source "${KWOKRC}"
}

# ------------------------------- STAGES -------------------------------------
stage_setup() {
  log init "setup start (cluster=${KWOK_CLUSTER} runtime=${KWOK_RUNTIME})"

  # Base packages
  log init "installing base packages"
  run_root "export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends git ca-certificates curl make python3 python3-pip python3-venv"

  # Clone repo (idempotent)
  if [ ! -d "${REPO_DIR}/.git" ]; then
    log init "cloning ${REPO_URL}#${REPO_BRANCH} -> ${REPO_DIR}"
    run_as "${TARGET_USER}" "git clone --branch '${REPO_BRANCH}' --single-branch '${REPO_URL}' '${REPO_DIR}'"
    run_root "chown -R '${TARGET_USER}:${TARGET_USER}' '${REPO_DIR}'"
  else
    log init "repo exists; pulling latest"
    run_as "${TARGET_USER}" "cd '${REPO_DIR}' && git fetch && git checkout '${REPO_BRANCH}' && git pull --ff-only || true"
  fi
  log ok "repo ready: ${REPO_DIR}"

  write_kwokrc
  read_kwokrc
  log ok ".kwokrc ready: cluster=${KWOK_CLUSTER} configs=${KWOK_CONFIGS} seeds=${KWOK_SEEDS} runtime=${KWOK_RUNTIME}"

  # kubectl + kwokctl + kwok
  log instal "installing kubectl ${KUBECTL_VERSION}, kwokctl+kwok ${KWOK_VERSION}"
  run_root "
    cd /tmp
    curl -fsSLo kubectl https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
    curl -fsSLO https://github.com/kubernetes-sigs/kwok/releases/download/${KWOK_VERSION}/kwokctl-linux-amd64
    curl -fsSLO https://github.com/kubernetes-sigs/kwok/releases/download/${KWOK_VERSION}/kwok-linux-amd64
    install -m 0755 kubectl /usr/local/bin/kubectl
    install -m 0755 kwokctl-linux-amd64 /usr/local/bin/kwokctl
    install -m 0755 kwok-linux-amd64   /usr/local/bin/kwok
    rm -f kubectl kwokctl-linux-amd64 kwok-linux-amd64
  "
  kubectl version --client=true >/dev/null 2>&1 || die "kubectl not installed"
  kwokctl --version >/dev/null 2>&1 || die "kwokctl not installed"
  kwok --version    >/dev/null 2>&1 || die "kwok not installed"
  log ok "kubectl/kwokctl/kwok installed"

  if [ "${KWOK_RUNTIME}" = "binary" ]; then
    # Go toolchain
    log instal "installing Go ${GO_VERSION}"
    run_root "
      curl -fsSLo /tmp/go.tgz https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
      rm -rf /usr/local/go
      tar -C /usr/local -xzf /tmp/go.tgz
      tee /etc/profile.d/golang.sh >/dev/null <<'EOF_G'
export PATH=\"/usr/local/go/bin:\$PATH\"
export GOPATH=\"\$HOME/go\"
export GOCACHE=\"\$HOME/.cache/go-build\"
EOF_G
      chmod 0644 /etc/profile.d/golang.sh
    "
    export PATH="/usr/local/go/bin:${PATH}"
    go version >/dev/null 2>&1 || die "go not installed"
    log ok "go installed"
  fi

  if [ "${KWOK_RUNTIME}" = "docker" ]; then
    # Docker engine
    log instal "installing Docker (runtime=docker)"
    run_root "
      install -m 0755 -d /etc/apt/keyrings
      if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      fi
      echo \"deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu \$(. /etc/os-release && echo \"\$UBUNTU_CODENAME\") stable\" > /etc/apt/sources.list.d/docker.list
      apt-get update
      apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io docker-buildx-plugin
      systemctl enable --now docker
    "
    docker --version >/dev/null 2>&1 || die "docker not installed"
    # ensure user can run docker
    if ! id -nG "${TARGET_USER}" | tr ' ' '\n' | grep -qx docker; then
      log init "adding ${TARGET_USER} to docker group"
      run_root "usermod -aG docker '${TARGET_USER}'"
    fi
    log ok "docker installed"
  fi

  # Python deps (always present; solver deps later for binary)
  log ok "setup complete"
}

stage_build() {
  read_kwokrc
  log build "start (runtime=${KWOK_RUNTIME})"

  if [ "${KWOK_RUNTIME}" = "binary" ]; then
    export PATH="/usr/local/go/bin:${PATH}"
    run_as "${TARGET_USER}" \
      "cd '${REPO_DIR}' && make build-scheduler GO_BUILD_ENV='CGO_ENABLED=0 GOOS=linux GOARCH=amd64'"
    log ok "built binary: ${REPO_DIR}/bin/kube-scheduler"

    # solver deps + copy to /opt/solver
    log instal "installing solver requirements (runtime=binary)"
    run_root "python3 -m pip install --no-cache-dir -r '${REPO_DIR}/scripts/mycrossnodepreemption/requirements.txt'"
    run_root "
      install -d -m 0755 /opt/solver
      cp -a '${REPO_DIR}/scripts/mycrossnodepreemption/.' /opt/solver/
      chown -R root:root /opt/solver
      chmod -R a+rX /opt/solver
    "
    log ok "solver staged at /opt/solver"

  else
    # docker image build
    run_as "${TARGET_USER}" \
      "cd '${REPO_DIR}' && DOCKER_BUILDKIT=1 docker build -t '${SCHED_IMAGE_TAG}' -f build/scheduler/Dockerfile ."
    log ok "image built: ${SCHED_IMAGE_TAG}"
  fi
}

stage_test() {
  read_kwokrc
  local KWOK_DIR="${REPO_DIR}/scripts/kwok"
  local TEST_GENERATOR="${KWOK_DIR}/kwok_test_generator.py"
  local KWOK_CONFIG_DIR="${KWOK_DIR}/configs/${KWOK_CONFIGS}"
  local SEED_FILE="${KWOK_DIR}/seeds/${KWOK_SEEDS}"
  local RESULTS_DIR="${RESULTS_DIR:-${REPO_DIR}/results}"

  log cfg "cluster=${KWOK_CLUSTER} runtime=${KWOK_RUNTIME}"
  log cfg "configs=${KWOK_CONFIG_DIR}"
  log cfg "seeds=${SEED_FILE}"
  log cfg "results=${RESULTS_DIR}"

  run_as "${TARGET_USER}" \
    "cd '${REPO_DIR}' && set -e; \\
    python3 '${TEST_GENERATOR}' \
      --cluster-name '${KWOK_CLUSTER}' \
      --kwok-runtime '${KWOK_RUNTIME}' \
      --config-dir '${KWOK_CONFIG_DIR}' \
      --results-dir '${RESULTS_DIR}' \
      --seed-file '${SEED_FILE}'"
  log ok "KWOK test done, results in ${RESULTS_DIR}"
}

# ------------------------------ DISPATCH ------------------------------------
cmd="${1:-all}"
case "$cmd" in
  setup-build) stage_setup; stage_build ;;
  test)   stage_test ;;
  all)    stage_setup; stage_build; stage_test ;;
esac
