#!/usr/bin/env bash
set -euo pipefail

# ---------- Defaults ----------
REPO_OWNER="${REPO_OWNER:-henrikdchristensen}"
REPO_NAME="${REPO_NAME:-scheduler-plugins}"
REPO_BRANCH="${REPO_BRANCH:-henrikdc-cross-preemp}"
REPO_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}"

KWOK_CLUSTER="${KWOK_CLUSTER:-kwok1}"
KWOK_RUNTIME="${KWOK_RUNTIME:-binary}"   # binary | docker
KWOK_CONFIG_DIR="${KWOK_CONFIG_DIR:-}"    # e.g. /path/to/scripts/kwok/configs/baseline
RESULTS_DIR="${RESULTS_DIR:-}"            # e.g. /path/to/results
SEED_FILE="${SEED_FILE:-}"                # e.g. /path/to/seeds.txt

KUBECTL_VERSION="${KUBECTL_VERSION:-v1.32.7}"
KWOK_VERSION="${KWOK_VERSION:-v0.7.0}"
GO_VERSION="${GO_VERSION:-1.24.3}"
GO_ARCH="${GO_ARCH:-amd64}"

SCHED_IMAGE_TAG="${SCHED_IMAGE_TAG:-localhost:5000/scheduler-plugins/kube-scheduler:dev}"

# ---------- Helpers ----------
log(){ printf '[%s] %s\n' "$1" "$2"; }
die(){ log error "$1"; exit 1; }
pick_target_user(){ if [ "$(id -u)" -eq 0 ]; then
  if [ -n "${SUDO_USER:-}" ] && [ "${SUDO_USER}" != "root" ]; then echo "$SUDO_USER"; return; fi
  getent passwd | awk -F: '$3>=1000 && $1!="nobody"{print $1; exit}'
else id -un; fi; }
run_root(){ if [ "$(id -u)" -eq 0 ]; then bash -lc "$*"; else sudo bash -lc "$*"; fi; }
run_as(){ local u="$1"; shift; if [ "$(id -un)" = "$u" ]; then bash -lc "$*"; else sudo -iu "$u" bash -lc "$*"; fi; }
is_abs() { [[ "$1" = /* ]]; }
abs_or_repo() {
  local p="$1"
  if [ -z "$p" ]; then echo ""; return; fi
  if is_abs "$p"; then
    printf '%s\n' "$(readlink -m -- "$p")"
  else
    printf '%s\n' "$(readlink -m -- "${REPO_DIR}/$p")"
  fi
}
resolve_input_paths() {
  KWOK_CONFIG_DIR="$(abs_or_repo "${KWOK_CONFIG_DIR}")"
  RESULTS_DIR="$(abs_or_repo "${RESULTS_DIR}")"
  SEED_FILE="$(abs_or_repo "${SEED_FILE}")"
}

# ---------- Command + Args ----------
cmd="all"
case "${1-}" in all|setup-build|test) cmd="$1"; shift
  esac
while [ $# -gt 0 ]; do
  case "$1" in
    --cluster=*)    KWOK_CLUSTER="${1#*=}";;
    --cluster)      KWOK_CLUSTER="$2"; shift;;
    --runtime=*)    KWOK_RUNTIME="${1#*=}";;
    --runtime)      KWOK_RUNTIME="$2"; shift;;
    --config-dir=*) KWOK_CONFIG_DIR="${1#*=}";;
    --config-dir)   KWOK_CONFIG_DIR="$2"; shift;;
    --results-dir=*)     RESULTS_DIR="${1#*=}";;
    --results-dir)       RESULTS_DIR="$2"; shift;;
    --seed-file=*)       SEED_FILE="${1#*=}";;
    --seed-file)         SEED_FILE="$2"; shift;;
  esac
  shift
done

# ---------- Paths ----------
TARGET_USER="${TARGET_USER:-$(pick_target_user)}"
[ -n "${TARGET_USER}" ] || die "could not resolve target user"
TARGET_HOME="$(eval echo "~${TARGET_USER}")"
REPO_DIR="${REPO_DIR:-${TARGET_HOME}/${REPO_NAME}}"
KWOKRC="${REPO_DIR}/.kwokrc"

# ---------- .kwokrc ----------
write_kwokrc() {
  cat > "${KWOKRC}" <<EOF
# Generated by bootstrap.sh
export KWOK_CLUSTER=${KWOK_CLUSTER}
export KWOK_RUNTIME=${KWOK_RUNTIME}
export KWOK_CONFIG_DIR=${KWOK_CONFIG_DIR}
export RESULTS_DIR=${RESULTS_DIR}
export SEED_FILE=${SEED_FILE}
export SCHED_IMAGE_TAG=${SCHED_IMAGE_TAG}
export SOLVER_PYTHON_BIN=/usr/local/bin/solver-python
EOF
  run_root "chown '${TARGET_USER}:${TARGET_USER}' '${KWOKRC}'"
}
read_kwokrc(){ [ -f "${KWOKRC}" ] || die "missing ${KWOKRC}"; source "${KWOKRC}"; }

# ---------- Stages ----------
stage_setup() {
  log init "setup (cluster=${KWOK_CLUSTER} runtime=${KWOK_RUNTIME})"
  run_root "export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends git ca-certificates curl make python3 python3-pip python3-venv"

  if [ ! -d "${REPO_DIR}/.git" ]; then
    log init "cloning https://github.com/${REPO_OWNER}/${REPO_NAME}#${REPO_BRANCH}"
    run_as "${TARGET_USER}" "git clone --branch '${REPO_BRANCH}' --single-branch '${REPO_URL}' '${REPO_DIR}'"
    run_root "chown -R '${TARGET_USER}:${TARGET_USER}' '${REPO_DIR}'"
  else
    run_as "${TARGET_USER}" "cd '${REPO_DIR}' && git fetch && git checkout '${REPO_BRANCH}' && git pull --ff-only || true"
  fi

  resolve_input_paths

  log cfg "resolved paths:"
  log cfg "  config-dir=${KWOK_CONFIG_DIR}"
  log cfg "  results-dir=${RESULTS_DIR}"
  log cfg "  seed-file=${SEED_FILE}"

  write_kwokrc
  read_kwokrc

  # kubectl/kwokctl/kwok
  run_root "
    cd /tmp
    curl -fsSLo kubectl https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
    curl -fsSLO https://github.com/kubernetes-sigs/kwok/releases/download/${KWOK_VERSION}/kwokctl-linux-amd64
    curl -fsSLO https://github.com/kubernetes-sigs/kwok/releases/download/${KWOK_VERSION}/kwok-linux-amd64
    install -m 0755 kubectl /usr/local/bin/kubectl
    install -m 0755 kwokctl-linux-amd64 /usr/local/bin/kwokctl
    install -m 0755 kwok-linux-amd64   /usr/local/bin/kwok
    rm -f kubectl kwokctl-linux-amd64 kwok-linux-amd64
  "
  kubectl version --client=true >/dev/null 2>&1 || die "kubectl not installed"
  kwokctl --version >/dev/null 2>&1 || die "kwokctl not installed"
  kwok --version    >/dev/null 2>&1 || die "kwok not installed"

  if [ "${KWOK_RUNTIME}" = "binary" ]; then
    run_root "
      curl -fsSLo /tmp/go.tgz https://go.dev/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz
      rm -rf /usr/local/go
      tar -C /usr/local -xzf /tmp/go.tgz
      tee /etc/profile.d/golang.sh >/dev/null <<'EOF_G'
export PATH=\"/usr/local/go/bin:\$PATH\"
export GOPATH=\"\$HOME/go\"
export GOCACHE=\"\$HOME/.cache/go-build\"
EOF_G
      chmod 0644 /etc/profile.d/golang.sh
    "
    export PATH="/usr/local/go/bin:${PATH}"
    go version >/dev/null 2>&1 || die "go not installed"
  else
    run_root "
      install -m 0755 -d /etc/apt/keyrings
      if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      fi
      echo \"deb [arch=\$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu \$(. /etc/os-release && echo \"\$UBUNTU_CODENAME\") stable\" > /etc/apt/sources.list.d/docker.list
      apt-get update
      apt-get install -y --no-install-recommends docker-ce docker-ce-cli containerd.io docker-buildx-plugin
      systemctl enable --now docker
    "
    docker --version >/dev/null 2>&1 || die "docker not installed"
    if ! id -nG "${TARGET_USER}" | tr ' ' '\n' | grep -qx docker; then
      run_root "usermod -aG docker '${TARGET_USER}'"
    fi
  fi

  log ok "setup complete"
}

stage_build() {
  read_kwokrc
  if [ "${KWOK_RUNTIME}" = "binary" ]; then
    # install solver deps to venv (PEP-668 safe)
    run_root "
      set -euo pipefail
      install -d -m 0755 /opt/solver
      cp -a '${REPO_DIR}/scripts/mycrossnodepreemption/.' /opt/solver/
      chmod -R a+rX /opt/solver

      python3 -m venv /opt/venv
      /opt/venv/bin/python -m pip install --upgrade pip
      /opt/venv/bin/pip install --no-cache-dir -r /opt/solver/requirements.txt

      # sanity check
      /opt/venv/bin/python -c 'import importlib, sys; print(sys.version); importlib.import_module("ortools"); print("sanity-ok")'
    "

    # build scheduler
    export PATH="/usr/local/go/bin:${PATH}"
    run_as "${TARGET_USER}" "cd '${REPO_DIR}' && make build-scheduler GO_BUILD_ENV='CGO_ENABLED=0 GOOS=linux GOARCH=amd64'"

    log ok "built binary and staged solver (venv)"
  else
    run_as "${TARGET_USER}" "cd '${REPO_DIR}' && DOCKER_BUILDKIT=1 docker build -t '${SCHED_IMAGE_TAG}' -f build/scheduler/Dockerfile ."
    log ok "image built: ${SCHED_IMAGE_TAG}"
  fi
}


stage_test() {
  read_kwokrc
  [ -n "${KWOK_CONFIG_DIR}" ] || die "--kwok-config-dir is required"
  [ -n "${RESULTS_DIR}" ]     || die "--results-dir is required"
  [ -n "${SEED_FILE}" ]       || die "--seed-file is required"

  local TEST_GENERATOR="${REPO_DIR}/scripts/kwok/kwok_test_generator.py"

  log cfg "cluster=${KWOK_CLUSTER} runtime=${KWOK_RUNTIME}"
  log cfg "configs=${KWOK_CONFIG_DIR}"
  log cfg "seeds=${SEED_FILE}"
  log cfg "results=${RESULTS_DIR}"

  run_as "${TARGET_USER}" "cd '${REPO_DIR}' && \
    /opt/venv/bin/python '${TEST_GENERATOR}' \
      --cluster-name '${KWOK_CLUSTER}' \
      --kwok-runtime '${KWOK_RUNTIME}' \
      --config-dir '${KWOK_CONFIG_DIR}' \
      --results-dir '${RESULTS_DIR}' \
      --seed-file '${SEED_FILE}'"
  log ok "KWOK test done"
}

# ---------- Dispatch ----------
case "${cmd}" in
  setup-build) stage_setup; stage_build ;;
  test)        stage_test ;;
  all)         stage_setup; stage_build; stage_test ;;
esac
