apiVersion: v1
kind: Pod
metadata:
  name: high-priority-pod8
  namespace: crossnode-test
spec:
  priorityClassName: p4
  restartPolicy: Never
  containers:
  - name: high-prio
    image: registry.k8s.io/pause:3.9
    resources:
      requests:
        cpu: 2000m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 1Gi