kind: KwokctlConfiguration
apiVersion: config.kwok.x-k8s.io/v1alpha1
options:
  kubeSchedulerImage: localhost:5000/scheduler-plugins/kube-scheduler:dev
  kubeSchedulerConfig: manifests/mycrossnodepreemption/sched-cc.yaml
componentsPatches:
  - name: kube-scheduler
    extraEnvs:
      - name: OPTIMIZE_CADENCE
        value: "in_batches" # choices: for_every, in_batches, continuous
      - name: OPTIMIZE_AT
        value: "preenqueue" # choices: preenqueue, postfilter
      - name: OPTIMIZATION_INTERVAL
        value: "30s"
      - name: OPTIMIZATION_INITIAL_DELAY
        value: "15s"
      - name: SOLVER_TIMEOUT
        value: "25s"
      - name: PLAN_EXECUTION_TIMEOUT
        value: "50s"