# pytest.ini
[pytest]
testpaths = 
    scripts/test
    scripts/kwok_integration_tests
addopts = --cov=scripts --cov-report=term-missing --cov-report=html:coverage/python
norecursedirs = bootstrap .venv venv