apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
profiles:
- schedulerName: secondary-scheduler
  plugins:
    filter:
      enabled:
      - name: NodeCRDResourceFit
      disabled:
      - name: "*"
    score:
      enabled:
      - name: NodeCRDResourceFit
      disabled:
      - name: "*"
