apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-ds
  namespace: crossnode-test
spec:
  priorityClassName: p4
  selector:
    matchLabels:
      app: demo-ds
  template:
    metadata:
      labels:
        app: demo-ds
    spec:
      priorityClassName: p4
      tolerations:
        - key: "kwok.x-k8s.io/node"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: c
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi
