kind: KwokctlConfiguration
apiVersion: config.kwok.x-k8s.io/v1alpha1
options:
  kubeSchedulerImage: localhost:5000/scheduler-plugins/kube-scheduler:dev
  kubeSchedulerConfig: manifests/mycrossnodepreemption/sched-cc.yaml
componentsPatches:
  - name: kube-scheduler
    extraEnvs:
      - name: OPTIMIZE_CADENCE
        value: "for_every" # choices: for_every, in_batches, continuous
      - name: OPTIMIZE_AT
        value: "postfilter" # choices: preenqueue, postfilter
      - name: OPTIMIZATION_INTERVAL
        value: "30s"
      - name: OPTIMIZATION_INITIAL_DELAY
        value: "15s"
      - name: SOLVER_TIMEOUT
        value: "400ms" # 25s
      - name: SOLVER_FAST_ENABLED
        value: "true"
      - name: SOLVER_PYTHON_ENABLED
        value: "false"
      - name: PLAN_EXECUTION_TIMEOUT
        value: "600s" # 50s