kind: KwokctlConfiguration
apiVersion: config.kwok.x-k8s.io/v1alpha1
options:
  kubeSchedulerImage: localhost:5000/scheduler-plugins/kube-scheduler:dev
  kubeSchedulerConfig: manifests/mycrossnodepreemption/sched-cc.yaml
componentsPatches:
  - name: kube-scheduler
    extraEnvs:
      - name: OPTIMIZE_CADENCE
        value: "in_batches" # choices: for_every, in_batches, continuously
      - name: OPTIMIZE_AT
        value: "postfilter" # choices: preenqueue, postfilter
      - name: OPTIMIZATION_INTERVAL
        value: "15s"
      - name: OPTIMIZATION_INITIAL_DELAY
        value: "20s"
      - name: PLAN_EXECUTION_TIMEOUT
        value: "600h" # 50s # TODO: set high to determine any potential issues
      - name: SOLVER_BFS_ENABLED
        value: "true"
      - name: SOLVER_BFS_TIMEOUT
        value: "200ms"
      - name: SOLVER_BFS_MAX_DEPTH
        value: "5"
      - name: SOLVER_BFS_MAX_VICTIMS_PER_NODE
        value: "-1" # -1 (unlimited)
      - name: SOLVER_BFS_MAX_DESTS_PER_LEVEL
        value: "-1" # -1 (unlimited)
      - name: SOLVER_BFS_MAX_SUCCESSORS_PER_STATE
        value: "-1" # -1 (unlimited)
      - name: SOLVER_BFS_MAX_FRONTIER_PER_DEPTH
        value: "-1" # -1 (unlimited)