kind: KwokctlConfiguration
apiVersion: config.kwok.x-k8s.io/v1alpha1
options:
  kubeSchedulerImage: localhost:5000/scheduler-plugins/kube-scheduler:dev
  kubeSchedulerConfig: manifests/mycrossnodepreemption/sched-cc.yaml
componentsPatches:
  - name: kube-scheduler
    extraEnvs:
      - name: OPTIMIZE_CADENCE
        value: "for_every" # choices: for_every, in_batches, continuously
      - name: OPTIMIZE_AT
        value: "preenqueue" # choices: preenqueue, postfilter
      - name: OPTIMIZATION_INTERVAL
        value: "15s"
      - name: OPTIMIZATION_INITIAL_DELAY
        value: "20s"
      - name: SOLVER_LOCAL_SEARCH_ENABLED
        value: "true"
      - name: SOLVER_LOCAL_SEARCH_TIMEOUT
        value: "200ms"
      - name: SOLVER_SWAP_MAX_VICTIMS_PER_NODE
        value: "8" # -1 (unlimited)
      - name: SOLVER_SWAP_MAX_TRIALS_PER_NODE
        value: "30"
      - name: SOLVER_SWAP_MAX_MOVES_FOR_PENDING_POD
        value: "5"
      - name: SOLVER_SWAP_MAX_TRIALS_PER_PENDING_POD
        value: "100"
      - name: PLAN_EXECUTION_TIMEOUT
        value: "600h" # 50s # TODO: set high to determine any potential issues