apiVersion: v1
kind: ServiceAccount
metadata:
  name: peaks
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: peaks-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: peaks
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: peaks-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: peaks
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: peaks-extension-apiserver
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: peaks
  namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
---
