name: Releases
on:
  push:
    tags:
    - v*

jobs:
  releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v3
      with:
         version: 'latest'
         token: ${{ secrets.GITHUB_TOKEN }}
      id: install
    - name: Package Helm Chart
      if: ${{ github.repository == 'kubernetes-sigs/scheduler-plugins' }}
      run: |
        helm package ./manifests/install/charts/as-a-second-scheduler
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "*.tgz"
