# +-------------------------------------------------------------------+
# | (C) Copyright IBM Corp. 2025, 2026                                |
# | SPDX-License-Identifier: Apache-2.0                               |
# +-------------------------------------------------------------------+

name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions: read-all

jobs:
  pre-commit:
    uses: ibm-aiu/spyre-operator-actions/.github/workflows/pre-commit.yaml@main
  unit-test:
    needs: pre-commit
    uses: ibm-aiu/spyre-operator-actions/.github/workflows/unit-test.yaml@main
  # # Add the following test when CRC E2E test is ready
  # e2e-test:
  #  needs: unit-test
  #  if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
  #  uses: ibm-aiu/spyre-operator-actions/.github/workflows/crc-e2e-test.yaml@main
